# Generated by Django 4.2.9 on 2024-12-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_product_remaining_alter_sales_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='counted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
