# Generated by Django 4.2.9 on 2024-12-18 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_sales_counted_amount_sales_difference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='given',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='received',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='remaining',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='spoiled',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='SupplierData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('liter', models.FloatField()),
                ('receivedtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Data',
                'verbose_name_plural': 'Customer Data',
            },
        ),
    ]
