# Generated by Django 4.2.9 on 2024-12-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_sales_amount_alter_sales_given_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierdata',
            options={'verbose_name': 'Supplier Data', 'verbose_name_plural': 'Supplier Data'},
        ),
    ]
