# Generated by Django 4.2.9 on 2024-12-19 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_alter_supplierdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_liters', models.FloatField(blank=True, null=True)),
                ('given_liters', models.FloatField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('from_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='home.shop')),
                ('to_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='home.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
