# Generated by Django 4.2.9 on 2024-12-19 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_storetransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetransfer',
            name='from_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='home.shop'),
        ),
        migrations.AlterField(
            model_name='storetransfer',
            name='given_liters',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='storetransfer',
            name='received_liters',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='storetransfer',
            name='to_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='home.shop'),
        ),
    ]
