# Generated by Django 4.2.9 on 2024-12-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_storetransfer_from_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='pokelewa',
            field=models.FloatField(default=0, null=True),
        ),
    ]
