# Generated by Django 4.2.9 on 2024-12-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_sales_pokelewa_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pokelewa',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
