# Generated by Django 4.2.9 on 2024-12-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_product_pokelewa_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='storetransfer',
            name='maziwa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplierdata',
            name='maziwa',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplierdata',
            name='liter',
            field=models.FloatField(default=0),
        ),
    ]
