# Generated by Django 4.2.9 on 2024-12-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_storetransfer_maziwa_supplierdata_maziwa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pokelewa',
            new_name='pokelewa_baridi',
        ),
        migrations.AddField(
            model_name='product',
            name='pokelewa_moto',
            field=models.FloatField(default=0),
        ),
    ]
