# Generated by Django 5.1.4 on 2025-02-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_pokelewa_product_pokelewa_baridi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='toka_baridi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='toka_moto',
            field=models.FloatField(default=0),
        ),
    ]
