# Generated by Django 5.1.4 on 2025-02-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_product_pokelewa_mgando_product_toka_mgando'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierdata',
            old_name='maziwa',
            new_name='milk_type',
        ),
        migrations.RemoveField(
            model_name='supplierdata',
            name='name',
        ),
        migrations.AddField(
            model_name='supplierdata',
            name='source_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierdata',
            name='source_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
