# Generated by Django 5.1.4 on 2025-02-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_maziwa_supplierdata_milk_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdata',
            name='source_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplierdata',
            name='source_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
