# Generated by Django 5.1.4 on 2025-02-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_supplierdata_source_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierdata',
            name='action_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
