# Generated by Django 5.1.4 on 2025-02-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_supplierdata_action_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierdata',
            old_name='receivedtime',
            new_name='created_at',
        ),
    ]
