# Generated by Django 5.1.4 on 2025-02-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rename_receivedtime_supplierdata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sold',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
