# Generated by Django 5.1.4 on 2025-02-14 13:16

from django.db import migrations
from django.db.models import F, Max
from django.utils import timezone

def migrate_counted_amounts(apps, schema_editor):
    Sales = apps.get_model('home', 'Sales')
    DailyCount = apps.get_model('home', 'DailyCount')
    
    # Get all unique combinations of date and shop, taking the latest counted_amount and user
    sales_data = Sales.objects.values(
        'created_at__date',
        'shop'
    ).annotate(
        # Get the latest counted_amount and corresponding user for each date/shop
        counted_amount=Max('counted_amount'),
        user=Max('user')  # Take the latest user who submitted
    ).filter(counted_amount__isnull=False)
    
    # Create DailyCount records
    for data in sales_data:
        DailyCount.objects.get_or_create(
            date=data['created_at__date'],
            shop_id=data['shop'],
            defaults={
                'counted_amount': data['counted_amount'],
                'user_id': data['user'],
                'created_at': timezone.now()
            }
        )

def reverse_migrate(apps, schema_editor):
    # We can't reverse this migration since we can't determine which Sales records
    # the counted_amount came from
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_dailycount'),  # Make sure this matches your previous migration
    ]

    operations = [
        migrations.RunPython(migrate_counted_amounts, reverse_migrate),
    ]
