# Generated by Django 5.1.4 on 2025-02-20 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
